package com.presaleagent.hook;

public enum HookEventType {
    SESSION_START, PRE_CONTEXT_ASSEMBLE, PRE_INTENT, PRE_RAG_SEARCH, PRE_CATALOG_SEARCH,
    PRE_AGENT_RUN, PRE_TOOL_CALL, POST_TOOL_CALL, PRE_RESPONSE_VERIFY, POST_RESPONSE,
    COMPACTION_START, COMPACTION_END
}
